baseurl = "http://daoran.github.io/"
languageCode = "en-us"
title = "daoran's blog"
theme = "hugo-steam-theme"
disqusShortname = ""
paginate = 10

[params]

	title = "daoran"
	subtitle = "never run with the crowd"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "blue"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Ryan Sui"
	bio = "making the world suck less."
	description = "Thoughts on programming & life"
	location = "" # optional
	twitter = "daoransky" # optional
	github = "daoran" # optional
    weibo = "daoransky" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
